name: Playwright

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      # SauceDemo defaults – override in repo Secrets if needed
      BASE_URL: https://www.saucedemo.com
      USERNAME: standard_user
      PASSWORD: secret_sauce
      # Optional: if you kept API tests
      API_URL: https://reqres.in/api
      # Playwright uses this to avoid interactive tools in CI
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install browsers
        run: npx playwright install --with-deps

      # OPTIONAL: speed up by running a single browser (Chromium)
      # Uncomment this block + the next test run block, and comment out the normal "Run tests"
      # - name: Update config to only run chromium (optional)
      #   run: |
      #     node -e "
      #       const fs=require('fs');
      #       let cfg=fs.readFileSync('playwright.config.ts','utf8');
      #       cfg=cfg.replace(/projects:\\s*\\[[\\s\\S]*?\\]/,'projects: [{ name: \\\"chromium\\\", use: { ...devices[\\\"Desktop Chrome\\\"] } }]');
      #       fs.writeFileSync('playwright.config.ts',cfg);
      #     "

      - name: Run tests
        run: npm test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/**/trace.zip
          retention-days: 7
